### ISSUE TITLE
1.20.6 – BeforeBubbleSendMessageEvent may only be triggered asynchronously

### ISSUE THREAD

**Issue by dimentyy** [whereareiam/Socialismus#36]
```
[00:09:02 ERROR]: [Socialismus] [ACF] Exception in command: socialismus bubble MESSAGE
[00:09:02 ERROR]: [Socialismus] [ACF] java.lang.IllegalStateException: BeforeBubbleSendMessageEvent may only be triggered asynchronously.
[00:09:02 ERROR]: [Socialismus] [ACF]   at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:40)
[00:09:02 ERROR]: [Socialismus] [ACF]   at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
[00:09:02 ERROR]: [Socialismus] [ACF]   at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:627)
[00:09:02 ERROR]: [Socialismus] [ACF]   at Sucialismus.jar//me.whereareiam.socialismus.core.module.bubblechat.BubbleQueue.addMessage(BubbleQueue.java:33)
[00:09:02 ERROR]: [Socialismus] [ACF]   at Sucialismus.jar//me.whereareiam.socialismus.core.module.bubblechat.BubbleChatService.distributeBubbleMessage(BubbleChatService.java:71)
[00:09:02 ERROR]: [Socialismus] [ACF]   at Sucialismus.jar//me.whereareiam.socialismus.core.command.commands.BubbleCommand.onCommand(BubbleCommand.java:63)
[00:09:02 ERROR]: [Socialismus] [ACF]   at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
[00:09:02 ERROR]: [Socialismus] [ACF]   at java.base/java.lang.reflect.Method.invoke(Unknown Source)
[00:09:02 ERROR]: [Socialismus] [ACF]   at co.aikar.commands.RegisteredCommand.invoke(RegisteredCommand.java:152)
[00:09:02 ERROR]: [Socialismus] [ACF]   at co.aikar.commands.BaseCommand.executeCommand(BaseCommand.java:578)
[00:09:02 ERROR]: [Socialismus] [ACF]   at co.aikar.commands.BaseCommand.execute(BaseCommand.java:513)
[00:09:02 ERROR]: [Socialismus] [ACF]   at co.aikar.commands.RootCommand.execute(RootCommand.java:99)
[00:09:02 ERROR]: [Socialismus] [ACF]   at co.aikar.commands.BukkitRootCommand.execute(BukkitRootCommand.java:84)
[00:09:02 ERROR]: [Socialismus] [ACF]   at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91)
[00:09:02 ERROR]: [Socialismus] [ACF]   at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
[00:09:02 ERROR]: [Socialismus] [ACF]   at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:30)
[00:09:02 ERROR]: [Socialismus] [ACF]   at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:13)
[00:09:02 ERROR]: [Socialismus] [ACF]   at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8)
[00:09:02 ERROR]: [Socialismus] [ACF]   at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5)
[00:09:02 ERROR]: [Socialismus] [ACF]   at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103)
[00:09:02 ERROR]: [Socialismus] [ACF]   at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:456)
[00:09:02 ERROR]: [Socialismus] [ACF]   at net.minecraft.commands.Commands.performCommand(Commands.java:363)
[00:09:02 ERROR]: [Socialismus] [ACF]   at net.minecraft.commands.Commands.performCommand(Commands.java:350)
[00:09:02 ERROR]: [Socialismus] [ACF]   at net.minecraft.commands.Commands.performCommand(Commands.java:345)
[00:09:02 ERROR]: [Socialismus] [ACF]   at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2282)
[00:09:02 ERROR]: [Socialismus] [ACF]   at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$18(ServerGamePacketListenerImpl.java:2256)
[00:09:02 ERROR]: [Socialismus] [ACF]   at net.minecraft.server.TickTask.run(TickTask.java:18)
[00:09:02 ERROR]: [Socialismus] [ACF]   at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)
[00:09:02 ERROR]: [Socialismus] [ACF]   at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
[00:09:02 ERROR]: [Socialismus] [ACF]   at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1546)
[00:09:02 ERROR]: [Socialismus] [ACF]   at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:195)
[00:09:02 ERROR]: [Socialismus] [ACF]   at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)
[00:09:02 ERROR]: [Socialismus] [ACF]   at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1523)
[00:09:02 ERROR]: [Socialismus] [ACF]   at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1446)
[00:09:02 ERROR]: [Socialismus] [ACF]   at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135)
[00:09:02 ERROR]: [Socialismus] [ACF]   at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1412)
[00:09:02 ERROR]: [Socialismus] [ACF]   at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1273)
[00:09:02 ERROR]: [Socialismus] [ACF]   at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326)
[00:09:02 ERROR]: [Socialismus] [ACF]   at java.base/java.lang.Thread.run(Unknown Source)
```

Server version: purpur `1.20.6-2227-79d199c (MC: 1.20.6)`
Plugin version: `1.3.7`

Error happens while executing this command: `/socialismus bubble MESSAGE`

**Comment by whereareiam** [comment]
Test new dev build, should be fixed now. If it works, close this issue.
https://github.com/whereareiam/Socialismus/actions/runs/9413755801

**Comment by dimentyy** [comment]
<img width="1157" alt="" src="https://github.com/whereareiam/Socialismus/assets/114256092/035f0aa1-643f-4d60-ac89-b556ef14782d">
<img width="1728" alt="" src="https://github.com/whereareiam/Socialismus/assets/114256092/af119af6-6d26-46d0-b4b9-c58e9ffcd381">


No errors in console and no bubbles appearing 🤔

---

Also an error occurs when sending the first message after joining (formatting works starting from the second message)

<img width="450" alt="Снимок экрана 2024-06-07 в 20 25 58" src="https://github.com/whereareiam/Socialismus/assets/114256092/269b00ef-fa45-4694-9199-c61c5a02e355">

```
[20:24:07 ERROR]: Could not pass event AsyncChatEvent to Socialismus v1.3.8
java.lang.UnsupportedOperationException: Unsupported server version: 1.20.6-R0.1-SNAPSHOT
        at Socialismus-PAPER-1.3.8.jar/me.whereareiam.socialismus.core.version.Version.getVersion(Version.java:32) ~[Socialismus-PAPER-1.3.8.jar:?]
        at Socialismus-PAPER-1.3.8.jar/me.whereareiam.socialismus.core.integration.protocollib.ProtocolVersion.getMetaVisibility(ProtocolVersion.java:24) ~[Socialismus-PAPER-1.3.8.jar:?]
        at Socialismus-PAPER-1.3.8.jar/me.whereareiam.socialismus.core.integration.protocollib.entity.metadata.EntityMetadataPacket.getMetadata(EntityMetadataPacket.java:28) ~[Socialismus-PAPER-1.3.8.jar:?]
        at Socialismus-PAPER-1.3.8.jar/me.whereareiam.socialismus.core.integration.protocollib.entity.metadata.display.DisplayMetadataPacket.getMetadata(DisplayMetadataPacket.java:26) ~[Socialismus-PAPER-1.3.8.jar:?]
        at Socialismus-PAPER-1.3.8.jar/me.whereareiam.socialismus.core.integration.protocollib.entity.metadata.display.TextDisplayMetadataPacket.getMetadata(TextDisplayMetadataPacket.java:51) ~[Socialismus-PAPER-1.3.8.jar:?]
        at Socialismus-PAPER-1.3.8.jar/me.whereareiam.socialismus.core.module.bubblechat.BubbleFactory.createBubble(BubbleFactory.java:66) ~[Socialismus-PAPER-1.3.8.jar:?]
        at Socialismus-PAPER-1.3.8.jar/me.whereareiam.socialismus.core.module.bubblechat.BubbleChatBroadcaster.broadcastBubble(BubbleChatBroadcaster.java:52) ~[Socialismus-PAPER-1.3.8.jar:?]
        at Socialismus-PAPER-1.3.8.jar/me.whereareiam.socialismus.core.module.bubblechat.BubbleQueue.processNextMessage(BubbleQueue.java:57) ~[Socialismus-PAPER-1.3.8.jar:?]
        at Socialismus-PAPER-1.3.8.jar/me.whereareiam.socialismus.core.module.bubblechat.BubbleQueue.addMessage(BubbleQueue.java:44) ~[Socialismus-PAPER-1.3.8.jar:?]
        at Socialismus-PAPER-1.3.8.jar/me.whereareiam.socialismus.core.module.bubblechat.BubbleChatService.distributeBubbleMessage(BubbleChatService.java:71) ~[Socialismus-PAPER-1.3.8.jar:?]
        at Socialismus-PAPER-1.3.8.jar/me.whereareiam.socialismus.core.listener.handler.ChatHandler.handleChatEvent(ChatHandler.java:45) ~[Socialismus-PAPER-1.3.8.jar:?]
        at Socialismus-PAPER-1.3.8.jar/me.whereareiam.socialismus.paper.listener.listeners.player.AsyncChatListener.onPlayerChatEvent(AsyncChatListener.java:50) ~[Socialismus-PAPER-1.3.8.jar:?]
        at Socialismus-PAPER-1.3.8.jar/me.whereareiam.socialismus.paper.listener.listeners.player.AsyncChatListener.onEvent(AsyncChatListener.java:38) ~[Socialismus-PAPER-1.3.8.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor228.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:1.20.6-2227-79d199c]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.6.jar:1.20.6-2227-79d199c]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.20.6.jar:1.20.6-2227-79d199c]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:627) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:378) ~[purpur-1.20.6.jar:1.20.6-2227-79d199c]
        at io.papermc.paper.adventure.ChatProcessor.processModern(ChatProcessor.java:151) ~[purpur-1.20.6.jar:1.20.6-2227-79d199c]
        at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:106) ~[purpur-1.20.6.jar:1.20.6-2227-79d199c]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2470) ~[purpur-1.20.6.jar:1.20.6-2227-79d199c]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.broadcastChatMessage(ServerGamePacketListenerImpl.java:2586) ~[purpur-1.20.6.jar:1.20.6-2227-79d199c]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChat$16(ServerGamePacketListenerImpl.java:2242) ~[purpur-1.20.6.jar:1.20.6-2227-79d199c]
        at net.minecraft.util.FutureChain.lambda$append$1(FutureChain.java:25) ~[purpur-1.20.6.jar:1.20.6-2227-79d199c]
        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
        at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
```

Ты же говоришь по-русски?

**Comment by whereareiam** [comment]
1. The bug should be fixed in the new dev build, try sending a bubble again.
2. Message without formatting could appear due to plugin conflicts, try to remove other plugins except PAPI & ProtocolLib.
3. Да и пишу тоже.

**Comment by dimentyy** [comment]
Странно...
Пропала команда `/socialismus reload`

<img width="945" alt="Снимок экрана 2024-06-07 в 21 53 44" src="https://github.com/whereareiam/Socialismus/assets/114256092/c2d3fc95-87a3-43f3-addc-4d1d75db6cb2">

И теперь при `/social bubble ...` (только один раз):

```
[21:49:26 INFO]: player issued server command: /socialismus bubble asdsad
[21:49:26 WARN]: [Socialismus] Plugin Socialismus v1.3.8 generated an exception while executing task 29
java.lang.UnsupportedOperationException: Unsupported server version: 1.20.6-R0.1-SNAPSHOT
        at Socialismus-PAPER-1.3.8.jar/me.whereareiam.socialismus.core.version.Version.getVersion(Version.java:34) ~[Socialismus-PAPER-1.3.8.jar:?]
        at Socialismus-PAPER-1.3.8.jar/me.whereareiam.socialismus.core.integration.protocollib.ProtocolVersion.getMetaVisibility(ProtocolVersion.java:24) ~[Socialismus-PAPER-1.3.8.jar:?]
        at Socialismus-PAPER-1.3.8.jar/me.whereareiam.socialismus.core.integration.protocollib.entity.metadata.EntityMetadataPacket.getMetadata(EntityMetadataPacket.java:28) ~[Socialismus-PAPER-1.3.8.jar:?]
        at Socialismus-PAPER-1.3.8.jar/me.whereareiam.socialismus.core.integration.protocollib.entity.metadata.display.DisplayMetadataPacket.getMetadata(DisplayMetadataPacket.java:26) ~[Socialismus-PAPER-1.3.8.jar:?]
        at Socialismus-PAPER-1.3.8.jar/me.whereareiam.socialismus.core.integration.protocollib.entity.metadata.display.TextDisplayMetadataPacket.getMetadata(TextDisplayMetadataPacket.java:51) ~[Socialismus-PAPER-1.3.8.jar:?]
        at Socialismus-PAPER-1.3.8.jar/me.whereareiam.socialismus.core.module.bubblechat.BubbleFactory.createBubble(BubbleFactory.java:66) ~[Socialismus-PAPER-1.3.8.jar:?]
        at Socialismus-PAPER-1.3.8.jar/me.whereareiam.socialismus.core.module.bubblechat.BubbleChatBroadcaster.broadcastBubble(BubbleChatBroadcaster.java:52) ~[Socialismus-PAPER-1.3.8.jar:?]
        at Socialismus-PAPER-1.3.8.jar/me.whereareiam.socialismus.core.module.bubblechat.BubbleQueue.processNextMessage(BubbleQueue.java:57) ~[Socialismus-PAPER-1.3.8.jar:?]
        at Socialismus-PAPER-1.3.8.jar/me.whereareiam.socialismus.core.module.bubblechat.BubbleQueue.addMessage(BubbleQueue.java:44) ~[Socialismus-PAPER-1.3.8.jar:?]
        at Socialismus-PAPER-1.3.8.jar/me.whereareiam.socialismus.core.module.bubblechat.BubbleChatService.distributeBubbleMessage(BubbleChatService.java:71) ~[Socialismus-PAPER-1.3.8.jar:?]
        at Socialismus-PAPER-1.3.8.jar/me.whereareiam.socialismus.core.command.commands.BubbleCommand.lambda$onCommand$0(BubbleCommand.java:67) ~[Socialismus-PAPER-1.3.8.jar:?]
        at Socialismus-PAPER-1.3.8.jar/me.whereareiam.socialismus.library.folialib.impl.SpigotImplementation.lambda$runAsync$1(SpigotImplementation.java:54) ~[Socialismus-PAPER-1.3.8.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:103) ~[purpur-1.20.6.jar:1.20.6-2227-79d199c]
        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.20.6.jar:1.20.6-2227-79d199c]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.20.6.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
        at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
```

**Comment by whereareiam** [comment]
Ошибку у себя не наблюдаю, команда на перезапуск тоже прекрасно работает.

У ProtocolLib'а сломаны текст дисплеи которые используются для баблов, поэтому они не появляются, жди пока полную поддержку 1.20.6 добавят.

<img width="1107" alt="image" src="https://github.com/whereareiam/Socialismus/assets/57540404/85bea3a0-027b-4549-9810-ed3174527928">

**Comment by dimentyy** [comment]
Окей, понял

**Comment by purpurcof** [comment]
Юзай PacketEvents дурачок

**Comment by whereareiam** [comment]
> Юзай PacketEvents дурачок

На момент написания плагина, PacketEvents не был особо популярен, поэтому и использовался ProtocolLib

**Comment by NeoFolia** [comment]
Как отключить частицы баблов когда пишешь в чат?

**Comment by whereareiam** [comment]
> Как отключить частицы баблов когда пишешь в чат?

Частиц никаких нет, скорей всего конфликт с другим плагином, если нужна помощь открывай issue или напиши мне в социальной сети.

**Comment by NeoFolia** [comment]
Очень странно. Удалил мод Socialism когда пишут в чат - баблов нет. Если отключаю функцию chatbubbles тоже частиц баблов нет когда пишет игрок. Ядро Folia.
